### PR TITLE
Add endpoint for project member scoped autocomplete

### PR DESCRIPTION
**Pull request by todtb**
https://github.com/inaturalist/inaturalist/issues/2670

Endpoint to be used to scope autocomplete of users by project membership. I'm not super familiar with swagger, so let me know if I'm missing anything.

### CODE REVIEW

**Comment by kueda** [comment]
This looks like it should work, but it also seems like a pretty niche case for an entirely new endpoint. Maybe adding a param like `project_id` to users/autocomplete and adding a few lines to that method would suffice here. Do you have an opinion that, @pleary?

**Comment by todtb** [comment]
@kueda Probably right. I think I was following the pattern of the `jquery` plugins with each autocomplete form element having it's own implementation. I think we could follow a pattern more like this: https://github.com/inaturalist/inaturalist/blob/62974c63c0e1671252216ffc7e27354b13289935/app/webpack/observations/identify/components/user_autocomplete.jsx#L12 and reduce it down to a single endpoint.

**Comment by pleary** [comment]
I agree that this new `/v1/projects/:id/members/autocomplete` endpoint would be better implemented as an optional parameter to the existing `/v1/users/autocomplete` endpoint, as `member_of_project_id` or something. Seems like most of the code is the same between the two methods except the filter on user ID, so perhaps extract that bit as it's own async method and have users autocomplete call it if this parameter is provided.

Similarly on the Rails end `project_user_autocomplete.js.erb` would then not be needed and could be implemented as an additional parameter used in the existing `user_autocomplete.js.erb`. That users autocomplete right now only sends the params `q`, `per_page`, and `order`, but those could be extended based on options if provided a `member_of_project_id` option for example (similar to how taxa autocomplete does for `notIDs` https://github.com/inaturalist/inaturalist/blob/master/app/assets/javascripts/jquery/plugins/inat/taxon_autocomplete.js.erb#L166).

As @kueda said it looks like this would work as-is, with documentation and all. But we can probably achieve the same with less code duplication, and less added documentation - you'll just need to document the one new parameter. Thanks for the submissions!

**Comment by todtb** [comment]
@kueda @pleary This is definitely dryer now (and may prove useful down the line).

**Comment by pleary** [comment]
Looks a lot better now. One thing I noticed is the project membership filter is only getting applied to one of two queries. There is an initial query that looks for exact matches of the search term again user login, and the membership filter is not being applied there. Therefore this method will currently return exact matches on username regardless of project membership.

Could you make sure this filter gets applied to both queries, and that exact matches are only returned with the user is a member of the project? After that we should be able to merge this in

**Comment by todtb** [comment]
Thanks @pleary, didn't even notice the exact match functionality until now. Too zeroed in I guess.

**Comment by kueda** [comment]
One issue that I (of course) noticed *after* merging is that you're limited by the number of project users returned by `project.members()`. That defaults to 30, so if the user you're searching for isn't in those first 30, you're out of luck, making this not work for very large projects like https://www.inaturalist.org/projects/city-nature-challenge-2020 (7823 members). Passing in `role=manager` will work (e.g. /v1/users/autocomplete?q=kes&project_id=40364&role=manager) for the specific case you're trying to solve, but there's still a general problem there.

One partial fix you could do that would also be a good security precaution is to do something like `const members = await project.members( { perPage: 1000, role: req.query.role } );`. I suspect doing this properly would require us to add `project_ids` to the users index, which might not be *too* bad, or at least not as bad as reindexing observations.

**Comment by todtb** [comment]
If we were to create a new index for users with `project_id`, I think the implementation of the endpoint would be simpler and the search optimized as well.

I agree that is the ideal way to do it. I'm assuming that this can be created ahead of time and then cutover without any downtime or performance degradation?

**Comment by kueda** [comment]
To my knowledge, we can't add or remove attributes to the indices without downtime, which is why I was recommending some less ideal fixes. IMO, just fetching 1000 members (or even 500) would probably solve the problem most of the time.

**Comment by kueda** [comment]
IMO, just adjust the limits. Downtime is something we need to schedule in advance and I'm not sure this small change is worth it. Not sure we've looked into the [Reindex API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) as a way to alter the indices, but maybe @pleary can comment on that. FWIW, our big indices are very big, so it's not clear to me what the performance implications would be of, say, having two copies of the observations index. Might be more doable for smaller indexes like users.

**Comment by todtb** [comment]
@kueda I've kinda been sitting on this to hear back if the user index route was feasible, as this endpoint with the `project_id` is to my knowledge not yet being used. 

However, if we go the other route, I'm a little confused by passing in the role. 

If the idea of https://github.com/inaturalist/inaturalist/issues/2670 is to allow granting a user of a project manager status, the only way to narrow down the results would be to look for users who aren't already managers, which I don't imagine would (proportionally) help filter very much. 

Is the idea then to just pass in the per_page option from https://github.com/inaturalist/inaturalist/issues/2670 ?

**Comment by kueda** [comment]
> I've kinda been sitting on this to hear back if the user index route was feasible, as this endpoint with the project_id is to my knowledge not yet being used.

I think I talked to Patrick about changing the users index and he seemed to think that was fine (I guess it's mostly just a problem for huge indexes like observations), so I think the additional work would be

- [ ] Add project_ids to User index definition
- [ ] Add project_ids to User#as_indexed_json
- [ ] Reindex the user whenever a ProjectUser gets created or destroyed
- [ ] Reindex all the users in a project when the project is destroyed
- [ ] Actually use this new index field in the API endpoint

Regarding the kind of stopgap approach, good point about the roles. And yes, I was mostly just suggesting upping that perPage option as I described [above](https://github.com/inaturalist/iNaturalistAPI/pull/195#issuecomment-636255431).

**Comment by todtb** [comment]
https://github.com/inaturalist/iNaturalistAPI/pull/198 open with the workaround. Thanks for the patience @kueda. I'd be happy to help with the indexing in the main app, but I don't think I know enough about the particulars of the ES setup to do it quickly/effectively. 

This sounds like it would handle most projects for now though.

**Pull request merged**
