### PR TITLE
Indicate the the 'observation search' request takes pagination parameters.

### PR DESCRIPTION
**Pull request by frewsxcv**
Assuming I'm reading the source correctly, this request does honor these parameters: 

https://github.com/inaturalist/iNaturalistAPI/blob/30987c8fe5b00b8a56ad7eb96c44402530efa5d6/openapi/schema/request/observations_search.js#L282-L296

### CODE REVIEW

**Comment by frewsxcv** [comment]
Hmm this might not be this simple, since the 'observation observers' endpoint also has `type = search`:

https://github.com/inaturalist/iNaturalistAPI/blob/30987c8fe5b00b8a56ad7eb96c44402530efa5d6/lib/views/swagger_v1.yml.ejs#L1003-L1004

...but has a different set of expected parameters:

https://github.com/inaturalist/iNaturalistAPI/blob/30987c8fe5b00b8a56ad7eb96c44402530efa5d6/openapi/schema/request/observations_observers.js#L5-L8

**Comment by frewsxcv** [comment]
@pleary If I recall correctly, I ran into this when using the `/observations/species_count` endpoint, which inherits much of the logic from observation search but doesn't include the pagination parameters

**Comment by frewsxcv** [comment]
And agreed the way I worded the original issue was not clear, sorry about that!

**Comment by pleary** [comment]
I pushed a commit fbcb988 where I explicitly add the `page` and `per_page` parameters for the species_count endpoint. They are now included in the V1 documentation https://api.inaturalist.org/v1/docs/#!/Observations/get_observations_species_counts . Does that look like it resolves the issue at hand here?

We have several endpoints that share a lot of the same parameters for filtering data, but not some of the more usability oriented parameters like ordering and sorting. OpenAPI/swagger doesn't have a great way of supporting the idea of reusable subsets of parameters, so the implementation here isn't as clean as I'd prefer. Thanks for making the pull request and raising the issue about the undocumented parameters!

**Comment by frewsxcv** [comment]
Perfect! Thank you so much @pleary 🌻

**Pull request closed without merging**
