### PR TITLE
fix: make pg_client actually use the configured DB name

### PR DESCRIPTION
**Pull request by tomsaleeba**
Everything "just works" until you change the name of the database from the default.

### CODE REVIEW

**Comment by tomsaleeba** [comment]
bump, I finally got around to fixing that failing test.

I found this because I've docker-ised this api and wanted to configure the whole db name from an env var.

**Comment by tomsaleeba** [comment]
No longer relevant after https://github.com/inaturalist/iNaturalistAPI/commit/e8ef2ed626708ac3b57542578fa4560b27233608#diff-5166e8b8f5e71eca82c8de22314dbcb1R24 made the same fix :tada:

**Comment by kueda** [comment]
Ah, sorry about that, Tom! If I'd merged in this PR back in January it would have saved me some grief. Alas. Hope all's well in your part of the world.

**Comment by tomsaleeba** [comment]
Hey, not a problem. I probably should've bumped this again, sorry.

We're doing good here. Sleepy old Adelaide is apparently the safest city in the world. Hope you're staying safe too.

**Pull request closed without merging**
