### PR TITLE
Update swagger_v1.yml.ejs with response limits

### PR DESCRIPTION
**Pull request by jwidness**
Adding documentation for endpoint limitations

### CODE REVIEW

**Comment by kueda** [comment]
@jwidness I think I'd prefer to change the behavior rather than update the docs here, so the identifications/:id endpoint will return up to 200 identifications like the observations/:id endpoint does. Work for you?

**Comment by kueda** [comment]
As far as I can tell this endpoint is returning up to 200 idents, so I'm going to close this.

**Comment by jwidness** [comment]
Sorry, missed your response.
For identifications/:id, it will only return 30 to a page (you can't change per_page), and it will only return page 1 (you can't get page 2), so the effect is that you can only access 30 results from this call.

The commit also had 5 other statements about limits: observations/:id, observations/identifiers, places/:id, projects/:id, and taxa/:id.

**Comment by kueda** [comment]
Sorry, I think I was looking at total_results and not counting actual results. I'll merge, though I still want to make the change to the behavior.

**Pull request merged**
